// <auto-generated />
using System;
using Meetopia.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Meetopia.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250901135807_ActivitiesSeed")]
    partial class ActivitiesSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Meetopia.Domain.Activities.Entities.Activity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("boolean");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Venue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Activities");

                    b.HasData(
                        new
                        {
                            Id = "activity-1",
                            Category = "drinks",
                            City = "London",
                            Date = new DateTime(2025, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Activity 2 months ago",
                            IsCancelled = false,
                            Latitude = 51.511716649999997,
                            Longitude = -0.1256611057818921,
                            Title = "Past Activity 1",
                            Venue = "The Lamb and Flag, 33, Rose Street, Seven Dials, Covent Garden, London, Greater London, England, WC2E 9EB, United Kingdom"
                        },
                        new
                        {
                            Id = "activity-2",
                            Category = "culture",
                            City = "Paris",
                            Date = new DateTime(2025, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Activity 1 month ago",
                            IsCancelled = false,
                            Latitude = 48.861147299999999,
                            Longitude = 2.3380276870466599,
                            Title = "Past Activity 2",
                            Venue = "Louvre Museum, Rue Saint-Honoré, Quartier du Palais Royal, 1st Arrondissement, Paris, Ile-de-France, Metropolitan France, 75001, France"
                        },
                        new
                        {
                            Id = "activity-3",
                            Category = "culture",
                            City = "London",
                            Date = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Activity 1 month in future",
                            IsCancelled = false,
                            Latitude = 51.496510900000004,
                            Longitude = -0.17600190725447445,
                            Title = "Future Activity 1",
                            Venue = "Natural History Museum"
                        },
                        new
                        {
                            Id = "activity-4",
                            Category = "music",
                            City = "London",
                            Date = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Activity 2 months in future",
                            IsCancelled = false,
                            Latitude = 51.502936649999995,
                            Longitude = 0.0032029278126681844,
                            Title = "Future Activity 2",
                            Venue = "The O2"
                        },
                        new
                        {
                            Id = "activity-5",
                            Category = "drinks",
                            City = "London",
                            Date = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Activity 3 months in future",
                            IsCancelled = false,
                            Latitude = 51.501778000000002,
                            Longitude = -0.053577,
                            Title = "Future Activity 3",
                            Venue = "The Mayflower"
                        },
                        new
                        {
                            Id = "activity-6",
                            Category = "drinks",
                            City = "London",
                            Date = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Activity 4 months in future",
                            IsCancelled = false,
                            Latitude = 51.512146650000005,
                            Longitude = -0.10364680647106028,
                            Title = "Future Activity 4",
                            Venue = "The Blackfriar"
                        },
                        new
                        {
                            Id = "activity-7",
                            Category = "culture",
                            City = "London",
                            Date = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Activity 5 months in future",
                            IsCancelled = false,
                            Latitude = 51.523762900000001,
                            Longitude = -0.15847430000000001,
                            Title = "Future Activity 5",
                            Venue = "Sherlock Holmes Museum, 221b, Baker Street, Marylebone, London, Greater London, England, NW1 6XE, United Kingdom"
                        },
                        new
                        {
                            Id = "activity-8",
                            Category = "music",
                            City = "London",
                            Date = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Activity 6 months in future",
                            IsCancelled = false,
                            Latitude = 51.543250499999999,
                            Longitude = -0.15197608174931165,
                            Title = "Future Activity 6",
                            Venue = "Roundhouse, Chalk Farm Road, Maitland Park, Chalk Farm, London Borough of Camden, London, Greater London, England, NW1 8EH, United Kingdom"
                        },
                        new
                        {
                            Id = "activity-9",
                            Category = "travel",
                            City = "London",
                            Date = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Activity 2 months ago",
                            IsCancelled = false,
                            Latitude = 51.5575525,
                            Longitude = -0.78140399999999999,
                            Title = "Future Activity 7",
                            Venue = "River Thames, England, United Kingdom"
                        },
                        new
                        {
                            Id = "activity-10",
                            Category = "film",
                            City = "London",
                            Date = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Activity 8 months in future",
                            IsCancelled = false,
                            Latitude = 51.5575525,
                            Longitude = -0.78140399999999999,
                            Title = "Future Activity 8",
                            Venue = "River Thames, England, United Kingdom"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
